Nexpo/Controllers/StudentSessionsController.cs

added new api call by request from frontend

Added studentsession timeslot api call for students

---

Nexpo.Tests/Controllers/EventsControllerTest.cs
Nexpo/Models/ApplicationDbContext.cs

Tests for the eventscontroller and uncommented ids in db seeding to be able to test the content of the data received with GET-requests. 
Discussion topics: 
1. Should it be required to be logged in to get events? 
2. How should we treat the generation of id:s in the seeding process? If we want it to be deterministic it seems like we have to manually assign it when creating the objects.

3.5 eventscontroller tests

---

Nexpo.Tests/Controllers/EventsControllerTest.cs
Nexpo.Tests/Controllers/StudentSessionsControllerTest.cs
Nexpo.Tests/Controllers/UsersControllerTest.cs
Nexpo/Models/ApplicationDbContext.cs

Made all ids of inserted entries to db deterministic by assigning them negative values. This should result in no conflicts when posting new entries in the tests as they then are only given random positive values. 
Additionally, are all tests relevant to this change now updated. 
Finally, validated that post-requests now work as intended in branch: 3.11-Ticketscontroller-tests, issue: #28 
Found this technique in the PostgreSQL documentation as a suggested solution to the seeding problem. 
Link: [https://www.npgsql.org/efcore/modeling/generated-properties.html#identity-sequence-options](https://www.npgsql.org/efcore/modeling/generated-properties.html#identity-sequence-options)

3.13 fix id generation for seeding data

---

Nexpo.Tests/Controllers/EventsControllerTest.cs
Nexpo.Tests/Controllers/StudentSessionsControllerTest.cs
Nexpo.Tests/Controllers/TicketsControllerTest.cs
Nexpo.Tests/Controllers/UsersControllerTest.cs
Nexpo/Models/ApplicationDbContext.cs

Added tests for the API against the TicketsController
**Note:** This branched contains the changes made in #36 as it was required to validate that post-requests now works as intended.

3.11 ticketscontroller tests

---

Nexpo/Controllers/CompaniesController.cs
Nexpo/DTO/PublicCompanyDto.cs
Nexpo/Models/Company.cs

2.1 relationship

---

Nexpo/Controllers/UsersController.cs

Fixed it by giving compnayRep access to get ALL users.
Will create a new issue which will consist of only giving access to a user if an application exists

comment out the faulty code that checks if application exists

---

Nexpo.Tests/Controllers/EventsControllerTest.cs
Nexpo/Controllers/EventsController.cs
Nexpo/DTO/NamedTicketDTO.cs
Nexpo/Models/Ticket.cs

did same workaround as Gustav and tested with fronted, works!

53 create ticket dto

---

Nexpo.Tests/Controllers/StudentSessionApplicationControllerTest.cs
Nexpo/Controllers/StudentSessionApplicationController.cs
Nexpo/Controllers/UsersController.cs
Nexpo/DTO/StudentSessionApplicationDto.cs
Nexpo/Models/Student.cs
Nexpo/Models/StudentSessionApplication.cs

More information added to tickets

50 send applicationdto instead of only sending application

---

Nexpo.Tests/Controllers/EventsControllerTest.cs

The changes made in the last pull request fixed the issues encountered with this test.

Uncommented GetAllTicketsAsAdmin() test since it now works

---

Nexpo/Controllers/StudentSessionApplicationController.cs
Nexpo/Services/EmailService.cs

Can't test on local as our email service is down :(
Suggestions on better email copy appreciated!

56 send email when student session application is accepted

---

Nexpo/Controllers/EventsController.cs
Nexpo/DTO/AddEventDTO.cs
Nexpo/Repositories/EventRepository.cs
UploadToDB/addCompanies.py
UploadToDB/addEvents.py
UploadToDB/login.py

Add events to db now possible and addCompany script fixed

Event backup

---

Nexpo/Controllers/StudentSessionTimeslotController.cs
Nexpo/DTO/CreateStudentSessionTimeslotAdminDto.cs
UploadToDB/addEvents.py
UploadToDB/addStudentSession.py

Upload studentsession works

---

Nexpo/AWS/Aws3Services.cs
Nexpo/AWS/IS3Configuration.cs
Nexpo/AWS/S3Config.cs
Nexpo/Controllers/FilesController.cs
Nexpo/Controllers/UsersController.cs
Nexpo/Controllers/s3BucketController.cs
Nexpo/DTO/UpdateUserDto.cs
Nexpo/Migrations/20221022172005_new migration.Designer.cs
Nexpo/Migrations/20221022172005_new migration.cs
Nexpo/Migrations/20221024212431_StudentSessionMotivations.Designer.cs
Nexpo/Migrations/ApplicationDbContextModelSnapshot.cs
Nexpo/Models/User.cs
Nexpo/Startup.cs

profile picture upload and delete

78 profile picture

---

Nexpo/Services/EmailService.cs

correct url for signup, password reset and general email

changed url (temporary solution)

---

Nexpo.Tests/Controllers/CompaniesControllerTest.cs
Nexpo/Controllers/CompaniesController.cs
Nexpo/Repositories/CompanyRepository.cs

Hampus want to delete companies.

Added new endpoint for deleting companies

---

Nexpo/Controllers/StudentSessionTimeslotController.cs
Nexpo/DTO/UpdateStudentSessionLocationDto.cs

Added UpdateLocation(id) that enables an admin to change the location on an already existing timeslot and added some tests to verify that this new behavior works as intended. 
The API call is: PUT api/timeslots/id with a location-string as payload. 
NOTE: This pull-request contains the changes made in #92

99 update timeslot

---

Nexpo/Controllers/TicketsController.cs
Nexpo/Repositories/TicketRepository.cs

Please double check, might be wrong

Added atomic transaction to TicketController

---

UploadToDB/addCompanies.py
UploadToDB/addEvents.py
UploadToDB/addStudentSession.py
UploadToDB/get_food_prefs.py
UploadToDB/login.py

can take event_id or get food preferences for all available events
closed #111

Script to get food preferences

---

README.md

Feel free to change if there is something I missed or misspelled anything.

Update README.md to include navigation links

---

Nexpo.Tests/Controllers/ContactControllerTest.cs
Nexpo.Tests/Controllers/ContactsControllerTest.cs
Nexpo.Tests/Controllers/EventsControllerTest.cs
Nexpo.Tests/Controllers/StudentSessionTimeslotControllerTest.cs
Nexpo.Tests/Controllers/UsersControllerTest.cs
runTests.sh

Implemented so only a specific class will be tested, if the dev desires (to reduce testing time)

Test parts
